### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by pasqal** [3liz/qgis_drain_sewer_visual_inspection#12]
Bonjour,
J'aimerais tester le plugin, mais je sèche sur son installation, y'a-t-il un tuto quelquepart ? Merci

**Comment by Gustry** [comment]
Bonjour,
Il y a un zip qui date de Octobre 2019 disponible dans le release : https://github.com/3liz/qgis_drain_sewer_visual_inspection/releases Il faut prendre le premier zip.

Ensuite, dans QGIS, gestionnaire des extensions, vous pouvez installer le ZIP.

Nous avons malheureusement du travail qui n'est pas encore intégré ici dans ce dépôt ici.
 N'hésitez pas à nous contacter pour plus d'information pour la lecture des fichiers ITV avec QGIS.

**Comment by pasqal** [comment]
ok, au temps pour moi, j'avais télécharger le master.zip
En passant, l'import regard ne reconnait pas les couches 3D (pointz)
