### ISSUE TITLE
Nouvelle symbologie pour geom_obs

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis_drain_sewer_visual_inspection#13]
Intégration d'une nouvelle stymbologie pour la couche geom_obs.
[geom_obs_qml.zip](https://github.com/3liz/qgis_drain_sewer_visual_inspection/files/5953049/geom_obs_qml.zip)

Funded by : Eau du Ponant

**Comment by Gustry** [comment]
Covered by f29abb3fe48a732e545f55cc98a1c44cadbaefcc ?

**Comment by rldhont** [comment]
Yes, done in f29abb3
