### ISSUE TITLE
Add create PostGIS tables algorithms

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis_drain_sewer_visual_inspection#7]
It will be insteresting to have two other algorithms:
* The first one is exactly the same as Create geopackage: creating all needed tables in a PostGIS database
* The second one creates postgis tables for specific layers and views for `geom_regard` and `geom_troncon` based on already exists PostGIS layers.

**Comment by Gustry** [comment]
The first bullet is done. User can choose between postgis (with a schema) or a geopackage.
The plugin will overwrite exisiting tables and view.

**Comment by Gustry** [comment]
From @rldhont on the chat:
> <reluc> pour l'histoire des vues - c'est comme un import de deonnées du point de vue du projet QGIS
<etrimaille> oui
<reluc> SI ta vue est dans le même schéma, à le même nom et à les même nom de colonne alors pour QGIS c'est apreil
<reluc> donc le script intervient dans le déroulé au même endroit
<reluc> après la config !
<reluc> DROP TABLE; CREATE VIEW AS
<reluc> tu peux tester sur la base raepa

Sorry @rldhont I like to keep track with a ticket ;-)

**Comment by Gustry** [comment]
Ok, the algorithm has been added by you in the meantime, sorry for the delay.
https://github.com/3liz/qgis_drain_sewer_visual_inspection/blob/master/processing_algorithms/load_postgis_layers_algorithm.py

Should we close the ticket?

PS, I have updated the `master` branch.

**Comment by rldhont** [comment]
It is not the same algorithm, `load_postgis_layers_algorithm.py` helps to load already exists postgis layers.

You can close this issue. We can't replace easily `geom_troncon` table by a view

**Comment by rldhont** [comment]
Can de closed
